name: Versioning

on:
  workflow_dispatch:
  release:
    types:
      - published
      - edited
      - created
      - released

jobs:
  create-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_latest_tag: true
