name: Versioning

on:
  release:

jobs:
  run-tag-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          publish_latest_tag: "true"
