name: Versioning

on:
  release:
    types: [published]

jobs:
  create-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v1
        with:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          publish_latest_tag: true
