name: Versioning

on:
  release:
    types:
      - published
      - edited

jobs:
  create-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
